user_status_for_staff_only:
  type: bool
  default: false
  description:
    en: "Restrict user status to staff only."

user_status_for_these_groups:
  type: list
  default: ""
  description:
    en: "Restrict user status to these groups."
